<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KIRAN" ignored="1" name="Test2" tests="3" failures="1" timestamp="2023-05-01T20:21:37 IST" time="12.458" errors="0">
  <testcase name="verifyInValidLogin" time="0.57" classname="tests.LoginTest">
    <skipped/>
  </testcase> <!-- verifyInValidLogin -->
  <testcase name="verifyInValidLogin" time="0.493" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at pages.LoginPage.login(LoginPage.java:44)
at tests.LoginTest.verifyInValidLogin(LoginTest.java:64)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyInValidLogin -->
  <testcase name="verifyValidLoginLogout" time="1.541" classname="tests.LoginTest"/>
  <testcase name="verifyValidLogin" time="0.0" classname="tests.LoginTest">
    <ignored/>
  </testcase> <!-- verifyValidLogin -->
</testsuite> <!-- Test2 -->
